apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jenkins.fullname" . }}-permanentagent-init-secret
  labels:
    "app.kubernetes.io/name": '{{ template "jenkins.name" .}}'
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ .Values.master.componentName }}"
data:
  init_slave.sh: |-
    {{ include "custom.init_slave.sh" . | b64enc }}
