{{- if .Values.permanentagent.sspmutualtls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jenkins.fullname" . }}-permanentagent-sspmutualtls-secret
  labels:
    "app.kubernetes.io/name": '{{ template "jenkins.name" .}}'
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ .Values.master.componentName }}"
data:
  sspcrt: |-
    {{ .Values.permanentagent.sspmutualtls.sspcrt }}
  p12passwd: |-
    {{ .Values.permanentagent.sspmutualtls.p12passwd }}
  nsspasswd: |-
    {{ .Values.permanentagent.sspmutualtls.nsspasswd }}
{{- end}}